import type { ProjectInput } from './projects'

// Tiptap doc builders
const t = (text: string) => ({ type: 'text', text })
const p = (text: string) => ({ type: 'paragraph', content: [t(text)] })
const h2 = (text: string) => ({ type: 'heading', attrs: { level: 2 }, content: [t(text)] })
const quote = (text: string) => ({ type: 'blockquote', content: [p(text)] })
const yt = (src: string) => ({ type: 'youtube', attrs: { src } })
const doc = (content: object[]) => ({ type: 'doc', content })

export const WORK_SEED: ProjectInput[] = [
  {
    title: 'Justach — a men’s grooming brand built around one *unforgettable symbol*.',
    slug: 'justach',
    client: 'Justach Salon & Spa',
    scope: 'Naming · Logo · Identity',
    year: '2025',
    credit_label: 'Studio',
    credit_value: 'Afterthought',
    case_label: 'Case 001',
    hero_color: '#541388',
    cover_image: null,
    summary: 'A men’s salon built around one unforgettable symbol.',
    status: 'draft',
    sort_order: 0,
    content: doc([
      p('Most men’s grooming brands reach for the same toolkit: a pair of scissors, a straight razor, a comb, some leather. Justach reached for something more ownable. Something that could sit on a business card, hang on a door, and still be immediately understood as belonging to one place.'),
      p('The brief was to build a modern salon & spa identity that felt masculine without being aggressive, premium without being cold, and memorable enough that clients would recognise it the second time they walked past.'),
      h2('Just + Moustache.'),
      p('The name came from the brand device itself. “Just” and “Moustache” compressed into a single word — sharp, direct, and effortless to say. It holds its shape at every size: on a storefront, in a notification, on a product label. And it does something most salon names don’t — it tells you exactly what kind of place this is before you walk in.'),
      p('A name that is also a category claim. Men’s grooming, owned.'),
      h2('The moustache as a brand device, not just a logo element.'),
      p('The most important decision in this project wasn’t the name, the typeface, or the palette. It was what we chose not to do with the moustache. We didn’t treat it as a decorative accessory — a small icon next to the wordmark, a vector tucked into a corner. We made it the system.'),
      p('The moustache appears inside the wordmark, becomes a repeating pattern, divides sections of a service menu, wraps packaging, hangs on a towel. Every customer touchpoint carries it. The result is an identity that doesn’t just represent the brand — it is the brand.'),
      h2('The colours no other men’s salon was using.'),
      p('Most men’s grooming brands live in a narrow range: black, white, charcoal, forest green, or gold. Each of those palettes communicates something, but they all say the same thing in different accents. We wanted a palette that was immediately ownable — something clients would associate only with Justach.'),
      p('Deep purple (#541388) gives the brand confidence and depth without the coldness of black or the loudness of red. Warm cream (#F1E9DA) brings it back to earth — a grooming warmth that feels considered, not clinical. Together they create contrast that reads premium while carrying genuine personality.'),
      h2('A grooming brand with a signature.'),
      p('The strongest identities have a symbol that works everywhere — not just on a screen or a business card, but on a towel, a product cap, a storefront window, a paper bag. Justach has that. The moustache is recognisable at 6 pixels and at 6 metres. It is the brand, and the brand is it.'),
      p('Clients who visit once leave knowing the name and the mark. That kind of recall is what every brand brief asks for, and very few identities actually deliver. Justach does.'),
    ]),
  },
  {
    title: 'The Pipeline Lab — thirty seconds to explain a *revenue engine*.',
    slug: 'pipelinelab',
    client: 'The Pipeline Lab',
    scope: 'Script · Motion Design',
    year: '2025',
    credit_label: 'Studio',
    credit_value: 'Afterthought',
    case_label: 'Case 002',
    hero_color: '#0A0614',
    cover_image: null,
    summary: 'Thirty seconds to explain a revenue engine.',
    status: 'draft',
    sort_order: 1,
    content: doc([
      p('Most agency intro videos say a lot and show very little. They list services, deploy words like “scalable” and “data-driven,” and leave the viewer roughly where they started. The brief for The Pipeline Lab required the opposite — one clear promise, delivered in thirty seconds, to a B2B audience of founders and sales leaders who have already been burned by agencies that overpromise.'),
      p('We handled both the script and the motion design. The challenge was to compress a genuinely complex service — outbound strategy, ICP targeting, lead generation, cold outreach systems, LinkedIn-led growth — into a visual narrative that felt credible without feeling like a slide deck.'),
      h2('A GTM agency that needed to out-perform its own pitch.'),
      p('The Pipeline Lab helps B2B companies build predictable outbound systems — not random lead activity, but qualified conversations, booked meetings, and sales-ready opportunities. Their clients are SaaS brands, service businesses, and growth teams. Their buyers are skeptical.'),
      p('The video needed to work across every surface: website hero, LinkedIn, pitch decks, outreach sequences. A single piece of content doing the job of a much longer explanation — earning trust in the first ten seconds and communicating the offer clearly by the last.'),
      h2('Start with the problem, not the solution.'),
      p('We structured the script around a single diagnostic question: why do most outbound programmes fail? The answer — inconsistent ICP targeting, weak messaging, no repeatable system — became the thirty-second arc. Each line had one job. Nothing was left in that didn’t earn its place.'),
      p('The goal was to make B2B buyers feel seen before the offer appeared. When a company recognises its own problem in the first few seconds, it stays for the solution. That sequencing — problem, cause, system, result — is what separates a sales video from a brand video. This needed to be both.'),
      yt('https://www.youtube.com/watch?v=XL-wrU8nrZk'),
      h2('The aesthetic of a well-run sales operation.'),
      p('The visual language had to feel like the inside of the agency itself — structured, sharp, and systematically executed. We avoided illustration and anything that read as “creative agency.” This was a performance business explaining a performance service to a performance audience.'),
      p('The style was built on clean layouts, bold kinetic typography, pipeline-inspired motion, and a dark-to-light palette with purple as the brand accent. Each transition was functional — it moved the argument forward rather than providing visual decoration. Abstract pipeline flows made the service feel tangible without making it literal.'),
      h2('One video. Every surface.'),
      p('The final thirty seconds works as a standalone brand introduction across every context The Pipeline Lab operates in — website hero, LinkedIn feed, pitch conversation, outreach sequence. It earns attention in the first ten seconds, explains the service in the next ten, and closes with a position that a B2B buyer can actually remember.'),
      p('A GTM agency that looks as sharp as the systems it sells.'),
    ]),
  },
  {
    title: 'Helio — from a brief about heat pumps to a brand about *hope*.',
    slug: 'helio',
    client: 'Helio Holdings',
    scope: 'Naming, Identity, Web',
    year: '2025',
    credit_label: 'Lead',
    credit_value: 'A. Gautam & T. Gidwani',
    case_label: 'Case 001',
    hero_color: 'var(--c-block-lime)',
    cover_image: null,
    summary: 'From a brief about heat pumps to a brand about hope.',
    status: 'draft',
    sort_order: 2,
    content: doc([
      p('A climate-tech holding company asked for a new name and identity for the moment they stopped being a “heat-pump installer” and started being something larger.'),
      h2('The brief'),
      p('The company had outgrown its first name. What had begun as a small installer of residential heat pumps was, four years on, three businesses under one roof — installation, manufacturing, and a small lending arm to help homeowners pay for any of it.'),
      p('The founders arrived at our first call with a brief that asked, politely, for a “more professional logo.” They left agreeing that what they actually needed was a single word the whole group could stand under, and a story honest enough to make the lending arm sound like the same company as the installers in the van.'),
      quote('“We don’t sell heat pumps. We sell the part of the house that finally feels like the future.” — Helio, internal brand line, 2025'),
      h2('The second thought'),
      p('Our first round had the obvious answers — earnest greens, leafy metaphors, the kind of identity that politely apologises for asking the homeowner to spend money. We made them well and then set them down.'),
      p('The second thought went the other way. Heat pumps are sun-shaped on a diagram. Lending is the same sun, on a longer timescale. The new name — Helio — covered all three businesses without translation, and the mark became a single solar disk: half-orange, half-night. Hope, and the hours it takes.'),
      h2('The system'),
      p('One mark, one wordmark, and a sub-system of three: Helio Home (installation), Helio Works (manufacturing), Helio Capital (lending). Each sub-brand is the same sun rotated. Three different times of day.'),
      p('The type system is built on two voices: a long, plain-spoken sans for the homeowner-facing side, and a tighter monospaced voice for the lending and manufacturing documents — the kind of language that earns trust by being less excited than the situation calls for.'),
      h2('The site'),
      p('The website was the second-largest piece of work after the name. Most climate sites are either selling fear or selling figures. Ours sells a calmer thing: the day after the install, the week after the loan, the room that finally feels right.'),
      p('It also does the boring work well — financing calculators, three different homeowner journeys, a press room, an investor section the lawyers signed off on without re-writing.'),
      h2('The outcome'),
      p('The new system launched in the autumn of 2025 across three markets — India, Germany, and a small pilot in the UK. The homeowner side of the business booked its strongest quarter in the four following weeks; the lending arm, which had been quietly invisible, took on its first institutional partner.'),
      p('It’s a project we’d happily do again, mostly because the founders made the second-best decision we’ve ever seen a client make: they let us throw away the first round of work in the first month.'),
    ]),
  },
  {
    title: 'Querida — a neighbourhood place that takes itself seriously, but *only just*.',
    slug: 'querida',
    client: 'Querida Restaurants',
    scope: 'Identity, Print, Menu',
    year: '2026',
    credit_label: 'Lead',
    credit_value: 'T. Gidwani & A. Gautam',
    case_label: 'Case 002',
    hero_color: 'var(--c-block-coral)',
    cover_image: null,
    summary: 'A neighbourhood place that takes itself seriously, but only just.',
    status: 'draft',
    sort_order: 3,
    content: doc([
      p('A small Spanish kitchen that had outgrown its first identity. We gave them a wordmark, a menu system, and a tone of voice that knows when to stop talking.'),
      h2('The brief'),
      p('Querida had been open for seven years on a quiet street in Bandra, Mumbai. The food was good, the room was full, and the identity — drawn in a hurry by a friend in 2018 — had stopped doing the work. The owner wanted a refresh ahead of a second site, but didn’t want to lose what made the first one feel like a neighbourhood place.'),
      p('The brief asked for a logo. We pushed back, gently, for a system that could be re-set by the owner every Tuesday morning without us in the room.'),
      quote('“It’s a Spanish word that means ‘darling’. Don’t make it precious about it.” — The owner, kickoff call, February 2026'),
      h2('The second thought'),
      p('The first round leaned into “darling” — the kind of warm, ribboned, hand-drawn identity you’ve seen on a hundred other restaurants. It was fine. We set it down.'),
      p('The second thought was a single italic wordmark, set in a serif that does most of the work, and one rule the whole system is built on: the menu changes every week, so the menu is the identity. Everything else stays out of its way.'),
      h2('The system'),
      p('One italic wordmark. One serif, one monospace, one paper colour. The dish names and the prices do everything else. The owner prints a fresh menu every Tuesday on a small Risograph in the back office — the same printer the team uses for the loyalty card, the Sunday lunch flyer, and the takeaway slip.'),
      p('We wrote a one-page guide. The owner has not called us about it since.'),
      h2('The room'),
      p('We made small, useful interventions to the room — a re-set of the signage, a new pendant for the bar, a paint colour for the back wall that matches the menu paper. The renovation happened over a single Sunday, between services. The regulars noticed in the right way: a few of them asked what was different, and most of them couldn’t quite say.'),
      h2('The outcome'),
      p('The second site — in Goa, a quieter version of the same kitchen — opened in May 2026. The identity moved with it, the menu changed, and the wordmark stayed the same italic. The owner has been kind enough to recommend us to two of her chef friends.'),
      p('It was the project that taught us a useful rule we now apply to all our restaurant work: don’t design the menu, design the way the menu changes.'),
    ]),
  },
]
